### ISSUE TITLE
Make rustdoc recognize the functions inside the same crate that has their example code

### ISSUE THREAD

**Issue by aev-mambro2** [aev-mambro2/mambro#4]
Currently running rustdoc --test on joor/download/orders outputs: 

```
running 2 tests                                   test src/main.rs - find_account_id (line 94) ... FAILED
test src/main.rs - find_third_party_id (line 140) ... FAILED
                                                  failures:

---- src/main.rs - find_account_id (line 94) stdout ----                                            error[E0463]: can't find crate for `orders`
 --> src/main.rs:95:1
  |                                               2 | extern crate orders;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate         
error: aborting due to previous error             
For more information about this error, try `rustc --explain E0463`.
thread 'src/main.rs - find_account_id (line 94)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:319:13                               note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- src/main.rs - find_third_party_id (line 140) stdout ----
error[E0425]: cannot find function `find_third_party_id` in module `crate`                           --> src/main.rs:147:20
  |
9 | let found = crate::find_third_party_id(&args);  |                    ^^^^^^^^^^^^^^^^^^^ not found in `crate`

error: aborting due to previous error             
For more information about this error, try `rustc --explain E0425`.                                 thread 'src/main.rs - find_third_party_id (line 140)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:319:13
                                                                                                    failures:
    src/main.rs - find_account_id (line 94)
    src/main.rs - find_third_party_id (line 140)  
test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out.
```

**Comment by aev-mambro2** [comment]
Not possible in current release, because that module is a binary rather than a library, and rustdoc handles that differently. If the module is a library, the code can import it. Otherwise it can't.
